openapi: 3.0.1
info:
  title: local-dev
  description: ''
  version: 1.0.0
tags:
  - name: demo
paths:
  /demo:
    get:
      summary: demo
      deprecated: false
      description: ''
      tags:
        - demo
      parameters: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    default: 200
                    examples:
                      - 200
                  msg:
                    type: string
                    nullable: true
                  data:
                    type: string
                required:
                  - code
                  - msg
                  - data
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers: []
