/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * local-dev
 * OpenAPI spec version: 1.0.0
 */
import * as axios from "axios"
import type { AxiosRequestConfig, AxiosResponse } from "axios"
export type GetDemo200 = {
  code: number
  data: string
  /** @nullable */
  msg: string | null
}

/**
 * @summary demo
 */
export const getDemo = <TData = AxiosResponse<GetDemo200>>(options?: AxiosRequestConfig): Promise<TData> => {
  return axios.default.get(`/demo`, options)
}

export type GetDemoResult = AxiosResponse<GetDemo200>
