/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * local-dev
 * OpenAPI spec version: 1.0.0
 */

export type GetDemo200 = {
  code: number
  data: string
  /** @nullable */
  msg: string | null
}
